using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WordsLives : MonoBehaviour
{
    private string[] spaceWords = {
    "spaceship",
    "planet",
    "asteroid",
    "galaxy",
    "star",
    "orbit",
    "warp",
    "laser",
    "black hole",
    "alien",
    "probe",
    "nebula",
    "hyperdrive",
    "cosmos",
    "satellite",
    "extraterrestrial",
    "supernova",
    "shuttle",
    "meteor",
    "astronaut",
    "command",
    "navigation",
    "exploration",
    "colony",
    "mining",
    "research",
    "trade",
    "battle",
    "fleet",
    "cruiser",
    "destroyer",
    "fighter",
    "battleship",
    "base",
    "facility",
    "cargo",
    "module",
    "docking",
    "shield",
    "energy",
    "propulsion",
    "radar",
    "scanner",
    "telemetry",
    "hull",
    "repair",
    "upgrade",
    "research",
    "discovery",
    "outpost",
    "terraform",
    "gravity",
    "atmosphere",
    "climate",
    "terrain",
    "biosphere",
    "civilization",
    "politics",
    "diplomacy",
    "intelligence",
    "espionage",
    "sabotage",
    "assassin",
    "rebel",
    "empire",
    "alliance",
    "colonization",
    "frontier",
    "horizon",
    "astronomy",
    "physics",
    "asteroid belt",
    "constellation",
    "cosmonaut",
    "debris",
    "derelict",
    "eclipse",
    "electromagnetic",
    "exoplanet",
    "extraction",
    "federation",
    "gravity well",
    "habitable",
    "interstellar",
    "ion propulsion",
    "jump gate",
    "launch",
    "light speed",
    "mass driver",
    "mining colony",
    "moon",
    "navigational beacon",
    "oxygen",
    "particle accelerator",
    "planetary defense",
    "quasar",
    "radiation",
    "red giant",
    "resources",
    "robot",
    "rocket",
    "solar system",
    "space station",
    "spacewalk",
    "star cluster",
    "sublight",
    "supercluster",
    "teleport",
    "terraforming",
    "transport",
    "wormhole"
};

public string GetNewWord(string newWord)
{
    int random = Random.Range(0, spaceWords.Length);
    newWord = spaceWords[random];
    return newWord;
}   

}
